[workspace]
members = [
    "bot_controller",
    "common",
    "k8s_controller",
    "proxy_controller",
    "sc2_controller"]

resolver = "2"

[workspace.package]
version = "0.4.5"
authors = ["danielvanschoor1997@gmail.com"]

