[workspace]
members = [
    "bot_controller",
    "common"
,
    "k8s_controller",
    "proxy_controller",
    "sc2_controller"]

[workspace.package]
version = "0.3.11"
authors = ["danielvanschoor1997@gmail.com"]
