[workspace]
members = [
    "bot_controller",
    "common",
    "k8s_controller",
    "proxy_controller",
    "sc2_controller"]

[workspace.package]
version = "0.4.4"
authors = ["danielvanschoor1997@gmail.com"]
