version: "3.9"
services:
  sc2_controller:
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./docker/Dockerfile
      target: sc2_controller
      args:
        CARGO_FLAGS: "${TEST_CARGO_FLAGS}"
    environment:
      - "ACSC2_PORT=8083"
      - "ACSC2_MATCH_CONTROLLER_HOST=match_controller"
    volumes:
      - "../testing-maps:/root/StarCraftII/maps"
      - "logs:/logs"

  bot_controller1:
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./docker/Dockerfile
      target: bot_controller
      args:
        CARGO_FLAGS: "${TEST_CARGO_FLAGS}"
    volumes:
      - "../aiarena-test-bots:/bots/bot1"
    environment:
      - "ACBOT_PORT=8081"
      - "ACBOT_MATCH_CONTROLLER_HOST=match_controller"
      - "ACBOT_GAME_HOST=sc2_controller"
      - "ACBOT_GAME_PORT=8083"

  bot_controller2:
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./docker/Dockerfile
      target: bot_controller
      args:
        CARGO_FLAGS: "${TEST_CARGO_FLAGS}"
    volumes:
      - "../aiarena-test-bots:/bots/bot2"
    environment:
      - "ACBOT_PORT=8082"
      - "ACBOT_MATCH_CONTROLLER_HOST=match_controller"
      - "ACBOT_GAME_HOST=sc2_controller"
      - "ACBOT_GAME_PORT=8083"

  match_controller:
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./docker/Dockerfile
      target: match_controller
      args:
        CARGO_FLAGS: "${TEST_CARGO_FLAGS}"
    environment:
      - "ACMATCH_PORT=8080"
      - "ACMATCH_BOT_CONT_1_HOST=bot_controller1"
      - "ACMATCH_BOT_CONT_2_HOST=bot_controller2"
      - "ACMATCH_SC2_CONT_HOST=sc2_controller"
    volumes:
      - "./test-matches:/app/matches"
      - "./test-config.toml:/app/config.toml"
      - "logs:/logs"

volumes:
     logs:
