apiVersion: batch/v1
kind: Job
metadata:
  name: PLACEHOLDER_JOB_NAME
  namespace: arenaclients
  labels:
    ac-name: PLACEHOLDER_API_CLIENT
    match-id: 'PLACEHOLDER_MATCH_ID'
spec:
  template:
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: 9000
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      initContainers:

        # This instance of match controller downloads all match assets 
        - name: match-is-loaded
          image: PLACEHOLDER_MATCH_CONTROLLER
          env:
            - name: ACMATCH_RUN_TYPE
              value: 'prepare'
            - name: ACMATCH_ARENA_CLIENT_ID
              value: 'PLACEHOLDER_API_CLIENT'
            - name: ACMATCH_API_TOKEN
              value: PLACEHOLDER_API_TOKEN
            - name: ACMATCH_LOGGING_LEVEL
              value: debug
            - name: ACMATCH_MATCHES_FILE
              value: ''
          volumeMounts:
            - mountPath: /app/config.toml
              name: config
              subPath: config.toml
            - mountPath: /bots
              name: bots
            - mountPath: /game
              name: game
            - mountPath: /logs
              name: logs
            - mountPath: /match
              name: match

        # The game controller starts the game engine
        # Env SC2PATH will be removed in next iteration
        - name: game-controller
          image: PLACEHOLDER_GAME_CONTROLLER
          restartPolicy: Always
          env:
            - name: PLAYER_1_SEAT
              value: '10001'
            - name: PLAYER_2_SEAT
              value: '10002'
            - name: SC2PATH
              value: /root/StarCraftII
          ports:
            - containerPort: 10001
            - containerPort: 10002
          readinessProbe:
            tcpSocket:
              port: 10002
          volumeMounts:
            - mountPath: /root/StarCraftII/maps
              name: game
            - mountPath: /logs
              name: logs
              subPath: game_controller
            - mountPath: /match
              name: match

        # Start bot controller for player 1
        - name: bot-controller-1
          image: PLACEHOLDER_BOT1_CONTROLLER
          restartPolicy: Always
          env:
            - name: BOT_NAME
              value: 'PLACEHOLDER_BOT1_NAME'
            - name: GAME_HOST
              value: 127.0.0.1
            - name: GAME_PORT
              value: '10001'
            - name: OPPONENT_ID
              value: 'PLACEHOLDER_BOT2_ID'
          resources:
            limits:
              cpu: '2'
            requests:
              cpu: '1'
          volumeMounts:
            - mountPath: /bot
              name: bots
              subPath: bot1/PLACEHOLDER_BOT1_NAME
            - mountPath: /logs
              name: logs
              subPath: bot-controller-1

        # Start bot controller for player 2
        - name: bot-controller-2
          image: PLACEHOLDER_BOT2_CONTROLLER
          restartPolicy: Always
          env:
            - name: BOT_NAME
              value: 'PLACEHOLDER_BOT2_NAME'
            - name: GAME_HOST
              value: 127.0.0.1
            - name: GAME_PORT
              value: '10002'
            - name: OPPONENT_ID
              value: 'PLACEHOLDER_BOT1_ID'
          resources:
            limits:
              cpu: '2'
            requests:
              cpu: '1'
          volumeMounts:
            - mountPath: /bot
              name: bots
              subPath: bot2/PLACEHOLDER_BOT2_NAME
            - mountPath: /logs
              name: logs
              subPath: bot-controller-2

      containers:

        # This instance of match controller submits match results
        - name: match-controller
          image: PLACEHOLDER_MATCH_CONTROLLER
          env:
            - name: ACMATCH_RUN_TYPE
              value: 'submit'
            - name: ACMATCH_ARENA_CLIENT_ID
              value: 'PLACEHOLDER_API_CLIENT'
            - name: ACMATCH_API_TOKEN
              value: PLACEHOLDER_API_TOKEN
            - name: ACMATCH_LOGGING_LEVEL
              value: debug
            - name: ACMATCH_MATCHES_FILE
              value: ''
          ports:
            - containerPort: 8080
              name: 8080tcp
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
          volumeMounts:
            - mountPath: /app/config.toml
              name: config
              subPath: config.toml
            - mountPath: /logs
              name: logs
            - mountPath: /bots
              name: bots
            - mountPath: /game
              name: game
            - mountPath: /match
              name: match

      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: PLACEHOLDER_CONFIGMAP_NAME
        - name: bots
          emptyDir: {}
        - name: game
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: match
          emptyDir: {}
