apiVersion: batch/v1
kind: Job
metadata:
  name: placeholder
  namespace: arenaclients
spec:
  template:
    spec:
      activeDeadlineSeconds: 9000
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      initContainers:
        - env:
            - name: ACBOT_PORT
              value: '8081'
            - name: ACBOT_MATCH_CONTROLLER_HOST
              value: 127.0.0.1
            - name: ACBOT_GAME_HOST
              value: 127.0.0.1
            - name: ACBOT_GAME_PORT
              value: '10001'
          image: aiarena/arenaclient-bot:latest
          name: bot-controller-1
          restartPolicy: Always
          ports:
            - containerPort: 8081
              name: 8081tcp
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
          resources:
            limits:
              cpu: '2'
            requests:
              cpu: '1'
          volumeMounts:
            - mountPath: /logs/bot_controller
              name: logs
              subPath: bot-controller-1
            - mountPath: /bots/bot1
              name: bots
              subPath: bot1
        - env:
            - name: ACBOT_PORT
              value: '8082'
            - name: ACBOT_MATCH_CONTROLLER_HOST
              value: 127.0.0.1
            - name: ACBOT_GAME_HOST
              value: 127.0.0.1
            - name: ACBOT_GAME_PORT
              value: '10002'
          image: aiarena/arenaclient-bot:latest
          name: bot-controller-2
          restartPolicy: Always
          ports:
            - containerPort: 8082
              name: 8082tcp
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
              scheme: HTTP
          resources:
            limits:
              cpu: '2'
            requests:
              cpu: '1'
          volumeMounts:
            - mountPath: /logs/bot_controller
              name: logs
              subPath: bot-controller-2
            - mountPath: /bots/bot2
              name: bots
              subPath: bot2
        - env:
            - name: ACSC2_PORT
              value: '8083'
            - name: ACSC2_MATCH_CONTROLLER_HOST
              value: 127.0.0.1
            - name: ACSC2_PLAYER_1_SEAT
              value: '10001'
            - name: ACSC2_PLAYER_2_SEAT
              value: '10002'
            - name: SC2PATH
              value: /root/StarCraftII
          image: aiarena/arenaclient-sc2:latest
          name: sc2-controller
          restartPolicy: Always
          ports:
            - containerPort: 8083
              name: 8083tcp
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
              scheme: HTTP
          volumeMounts:
            - mountPath: /logs/sc2_controller
              name: logs
              subPath: sc2_controller
            - mountPath: /root/StarCraftII/maps
              name: game
      containers:
        - env:
            - name: ACMATCH_PORT
              value: '8080'
            - name: ACMATCH_ARENA_CLIENT_ID
              value: ''
            - name: ACMATCH_API_TOKEN
              value: placeholder
            - name: ACMATCH_SC2_CONT_PORT
              value: '8083'
            - name: ACMATCH_LOGGING_LEVEL
              value: debug
          image: aiarena/arenaclient-match:latest
          name: match-controller
          ports:
            - containerPort: 8080
              name: 8080tcp
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
          volumeMounts:
            - mountPath: /app/config.toml
              name: config
              subPath: config.toml
            - mountPath: /logs
              name: logs
            - mountPath: /bots
              name: bots
            - mountPath: /game
              name: game
          __active: true
      restartPolicy: Never
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: placeholder
        - name: bots
          emptyDir: {}
        - name: game
          emptyDir: {}
        - name: logs
          emptyDir: {}
  backoffLimit: 6
__clone: true