apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-controller-config
  annotations:
    {}
  labels:
    {}
  namespace: arenaclients
data:
  config.toml: |-
    OLD_MATCH_DELETE_AFTER_MINUTES = 10
    JOB_PREFIX= "staging"
    WEBSITE_URL= "https://staging.aiarena.net"
    NAMESPACE= "arenaclients"
    ARENACLIENTS_JSON_PATH = "arenaclients.json"
    INTERVAL_SECONDS = 30