resources:
- ../../base
- configmap.yaml
namespace: arenaclients
images:
- name: aiarena/k8s-controller
  newTag: v0.3.0
nameSuffix: -staging
commonLabels:
  app: aiarena-k8s-controller-staging
patchesStrategicMerge:
  - patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization