apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-controller
  namespace: arenaclients
spec:
  template:
    spec:
      volumes:
        - name: arenaclients-json
          secret:
            defaultMode: 420
            optional: false
            secretName: arenaclients-secrets-staging
        