[package]
name = "sc2_controller"
version.workspace = true
authors.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { workspace=true }
serde = { workspace=true, features = ["derive"] }
utoipa = { workspace=true, features = ["axum_extras"], optional=true }
utoipa-swagger-ui = { workspace=true,  features = ["axum"], optional=true }
axum = { workspace=true }
tokio = { workspace=true}#, features = ["macros", "rt-multi-thread", "fs"] }
tower = { workspace=true}#, features = ["util", "timeout"] }
tracing = { workspace=true }
tracing-subscriber = { workspace=true, features = ["env-filter"] }
tracing-appender = { workspace=true }
reqwest = { workspace=true, features=["json"]}
tower-http = { workspace=true, features = ["add-extension", "trace"] }
tokio-util = { workspace=true, features = ["full"] }
tempfile = { workspace=true }

[features]
swagger = ["utoipa", "utoipa-swagger-ui"]