[package]
name = "proxy_controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common", features = ["ws", "reqwest_stream", "reqwest_multipart"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0.87"
tokio-tungstenite = "0.18.0"
sc2-proto = { git = "https://github.com/aiarena/sc2-proto-rs.git" }
protobuf = { version = "=3.2.0", features = ["with-bytes"] }
indexmap = { version = "1.9.2", features = ["serde"] }

[features]
swagger = ["common/swagger"]
