name: "Tag"

on:
  push:
    branches:
      - "master"

jobs:
  create-tag:
    name: "Create tag"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Get tag"
        id: "get-tag"
        shell: "bash"
        run: |
          echo PKG_VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml) >> $GITHUB_OUTPUT

      - name: "Set Tag"
        shell: "bash"
        run: |
          PKG_VERSION=${{ steps.get-tag.outputs.PKG_VERSION }}
          PKG_VERSION=${PKG_VERSION//$'\015'}
          if ! [ $(git tag -l v$PKG_VERSION) ]; then git tag v$PKG_VERSION && git push --tags; fi
